import { Inter } from 'next/font/google'; // Import Inter font
import localFont from 'next/font/local';  // Import localFont
import Navbar from './components/Navbar'; // Import Navbar component
import "./globals.css";

// Define the Inter font
const inter = Inter({
  subsets: ['latin'],
});

// Define local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
export const metadata = {
  title: "Todo Next App",
  description: "Generated by create next app",
};

// RootLayout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Apply the Inter font */}
        <Navbar /> {/* Ensure the Navbar component is imported */}
        {children}
      </body>
    </html>
  );
}
